// <auto-generated />
using System;
using System.Collections.Generic;
using ExMart_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExMart_Backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExMart_Backend.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("addToCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Garments",
                            IconPath = "icons/garments.png"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Stationary",
                            IconPath = "icons/stationary.png"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Appliances",
                            IconPath = "icons/appliance.png"
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.ColourMaster", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ColorId");

                    b.ToTable("ColourMaster");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorCode = "#FF0000",
                            ColorName = "red"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorCode = "#0000FF",
                            ColorName = "blue"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorCode = "#FFFFFF",
                            ColorName = "white"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorCode = "#000000",
                            ColorName = "black"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorCode = "#008000",
                            ColorName = "green"
                        },
                        new
                        {
                            ColorId = 6,
                            ColorCode = "#8F00FF",
                            ColorName = "violet"
                        },
                        new
                        {
                            ColorId = 7,
                            ColorCode = "#FFFF00",
                            ColorName = "yellow"
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Product_StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("Product_StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ExMart_Backend.Model.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductRateId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ColorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ExMart_Backend.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Color")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PrimaryImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Size")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Experion",
                            CategoryId = 1,
                            Color = new List<string> { "red", "black" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Experion branded t-shirt",
                            IsActive = true,
                            Name = "Experion Tshirt",
                            Price = 1499.00m,
                            PrimaryImageUrl = "staticimages/pro_tshirt.png",
                            Size = new List<string> { "15.6 inches" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 500m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Experion",
                            CategoryId = 1,
                            Color = new List<string> { "white" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Experion branded hoodie",
                            IsActive = true,
                            Name = "Hoody Experion brand",
                            Price = 399.99m,
                            PrimaryImageUrl = "https://media.karousell.com/media/photos/products/2023/4/29/gildan_zipup_hoodie_1682750904_29598b39.jpg",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 600m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Experion",
                            CategoryId = 1,
                            Color = new List<string> { "black", "red" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Experion branded jersey",
                            IsActive = true,
                            Name = "Jersey Experion branded",
                            Price = 399.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/51C2ieRiU9L.jpg",
                            Size = new List<string> { "40mm", "44mm" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 400m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Swiss Military",
                            CategoryId = 3,
                            Color = new List<string> { "white", "blue" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Swiss military branded earpods",
                            IsActive = true,
                            Name = "Earpods Swiss military",
                            Price = 349.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/71RFdy6y6LL._SL1500_.jpg",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 50m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "VAFS",
                            CategoryId = 2,
                            Color = new List<string> { "blue", "white", "green" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Reusable water bottle",
                            IsActive = true,
                            Name = "Water Bottle",
                            Price = 399.00m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/71zFvtVuP1L._SL1500_.jpg",
                            Size = new List<string> { "41mm", "45mm" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 300m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "VAFS",
                            CategoryId = 2,
                            Color = new List<string> { "Black", "red" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Insulated flask",
                            IsActive = true,
                            Name = "Flask",
                            Price = 349.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/41W9B1Ri4hL.jpg",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 400m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Nike",
                            CategoryId = 2,
                            Color = new List<string> { "White", "Black", "Red" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Nike Air Force 1 sneakers",
                            IsActive = true,
                            Name = "Nike Air Force 1",
                            Price = 99.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/61t0gIsFpjL._SY675_.jpg",
                            Size = new List<string> { "5", "6", "7", "8", "9", "10", "11", "12" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 800m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Color = new List<string> { "black", "White" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Samsung wireless earbuds",
                            IsActive = true,
                            Name = "Samsung Galaxy Buds 2 Pro",
                            Price = 1999.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/61KVX-MbIUL._SL1500_.jpg",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 23, 15, 22, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 50m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "VAFS",
                            CategoryId = 2,
                            Color = new List<string> { "Black", "White" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Personal diary",
                            IsActive = true,
                            Name = "Diary",
                            Price = 149.99m,
                            PrimaryImageUrl = "https://m.media-amazon.com/images/I/61eYApdaTDL._SL1100_.jpg",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 200m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "VAFS",
                            CategoryId = 2,
                            Color = new List<string> { "Black", "White" },
                            CreatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Multi-purpose backpack",
                            IsActive = true,
                            Name = "BackPack",
                            Price = 149.99m,
                            PrimaryImageUrl = "staticimages/pro_bag.png",
                            Size = new List<string> { "Standard" },
                            UpdatedAt = new DateTime(2023, 11, 22, 13, 37, 0, 0, DateTimeKind.Utc),
                            VendorId = 1,
                            Weight = 700m
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.ProductImages", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageUrl = " https://assets.ajio.com/medias/sys_master/root/20240202/XzVa/65bd163a8cdf1e0df5e313a0/-1117Wx1400H-442273276-black-MODEL7.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 11,
                            ImageUrl = "https://assets.ajio.com/medias/sys_master/root/20240202/T3LR/65bd18b616fd2c6e6ad4ea90/-473Wx593H-442273276-black-MODEL2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 12,
                            ImageUrl = "https://assets.ajio.com/medias/sys_master/root/20240202/0iIg/65bd0e568cdf1e0df5e2e7f1/-473Wx593H-442273276-black-MODEL6.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            ImageUrl = " https://m.media-amazon.com/images/I/51XQKBTbJ7L._SX569_.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 13,
                            ImageUrl = " https://m.media-amazon.com/images/I/51U6dpsRaFL._SX569_.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 14,
                            ImageUrl = " https://m.media-amazon.com/images/I/51Nd4BLQelL._SX569_.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/915Qebmr9XL._SX679_.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 15,
                            ImageUrl = "https://m.media-amazon.com/images/I/915Qebmr9XL._SX679_.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 16,
                            ImageUrl = "https://m.media-amazon.com/images/I/91RWzNCIEhL._SX679_.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/61F5lcvJHLL._SX522_.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 17,
                            ImageUrl = "https://m.media-amazon.com/images/I/61vBE3t4x1L._SX522_.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 18,
                            ImageUrl = "https://m.media-amazon.com/images/I/71QZbcvD65L._SX522_.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/51caXIXHv0L._SX679_.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 19,
                            ImageUrl = "https://m.media-amazon.com/images/I/614uQNgsIbL._SX679_.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 20,
                            ImageUrl = "https://m.media-amazon.com/images/I/616+eQhVmFL._SX679_.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/51zrU3wXApL._SX679_.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 21,
                            ImageUrl = "https://m.media-amazon.com/images/I/61h02o8qvAL._SX679_.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 22,
                            ImageUrl = "https://m.media-amazon.com/images/I/71kg31YtFHL._SX679_.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/61ZkbRBEBvL._SY675_.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 23,
                            ImageUrl = "https://m.media-amazon.com/images/I/81rLH99Wj2L._SY675_.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 24,
                            ImageUrl = "https://m.media-amazon.com/images/I/61R2cfPmcSL._SY675_.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/61lEskbCaoL._SY450_.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 25,
                            ImageUrl = "https://m.media-amazon.com/images/I/51wp23mi8qL._SY450_.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 26,
                            ImageUrl = "https://m.media-amazon.com/images/I/71YCCEPBguL._SY450_.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/516HwL0zZhL._SY450_.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 27,
                            ImageUrl = "https://m.media-amazon.com/images/I/6190STfffwL._SY450_.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 28,
                            ImageUrl = "https://m.media-amazon.com/images/I/61Lo553SSIL._SY450_.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 10,
                            ImageUrl = "https://example.com/gproxsuperlight_1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            ImageId = 29,
                            ImageUrl = "https://example.com/gproxsuperlight_1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            ImageId = 30,
                            ImageUrl = "https://example.com/gproxsuperlight_2.jpg",
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.ProductStatus", b =>
                {
                    b.Property<int>("ProductStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductStatusID"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductStatusID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ExMart_Backend.Model.SizeMaster", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SizeId"));

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SizeId");

                    b.ToTable("SizeMaster");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            Size = "XS"
                        },
                        new
                        {
                            SizeId = 2,
                            Size = "S"
                        },
                        new
                        {
                            SizeId = 3,
                            Size = "M"
                        },
                        new
                        {
                            SizeId = 4,
                            Size = "L"
                        },
                        new
                        {
                            SizeId = 5,
                            Size = "XL"
                        },
                        new
                        {
                            SizeId = 6,
                            Size = "XXL"
                        },
                        new
                        {
                            SizeId = 7,
                            Size = "XXXL"
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.StatusMaster", b =>
                {
                    b.Property<int>("Product_StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Product_StatusId");

                    b.ToTable("StatusMaster");

                    b.HasData(
                        new
                        {
                            Product_StatusId = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Product_StatusId = 2,
                            StatusName = "Shipped"
                        },
                        new
                        {
                            Product_StatusId = 3,
                            StatusName = "Delivered"
                        });
                });

            modelBuilder.Entity("ExMart_Backend.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt");
                    modelBuilder.Entity("ExMart_Backend.Model.User", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                            b.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b.HasKey("UserId");

                            b.ToTable("Users");

                            b.HasData(
                                new
                                {
                                    UserId = 1,
                                    CreatedAt = new DateTime(2024, 12, 29, 10, 40, 37, 49, DateTimeKind.Utc).AddTicks(2758),
                                    Email = "johndoe@example.com",
                                    Name = "John Doe",
                                    Phone = "1234567890"
                                },
                                new
                                {
                                    UserId = 2,
                                    CreatedAt = new DateTime(2024, 12, 29, 10, 40, 37, 49, DateTimeKind.Utc).AddTicks(2762),
                                    Email = "janesmith@example.com",
                                    Name = "Jane Smith",
                                    Phone = "0987654321"
                                },
                                new
                                {
                                    UserId = 3,
                                    CreatedAt = new DateTime(2024, 12, 29, 10, 40, 37, 49, DateTimeKind.Utc).AddTicks(2763),
                                    Email = "alicebrown@example.com",
                                    Name = "Alice Brown",
                                    Phone = "1122334455"
                                });
                            b.HasKey("Id");

                            b.ToTable("Users");
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                        {
                            b.Property<string>("Id")
                                .HasColumnType("text");

                            b.Property<string>("ConcurrencyStamp")
                                .IsConcurrencyToken()
                                .HasColumnType("text");

                            b.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.Property<string>("NormalizedName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.HasKey("Id");

                            b.HasIndex("NormalizedName")
                                .IsUnique()
                                .HasDatabaseName("RoleNameIndex");

                            b.ToTable("AspNetRoles", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                            b.Property<string>("ClaimType")
                                .HasColumnType("text");

                            b.Property<string>("ClaimValue")
                                .HasColumnType("text");

                            b.Property<string>("RoleId")
                                .IsRequired()
                                .HasColumnType("text");

                            b.HasKey("Id");

                            b.HasIndex("RoleId");

                            b.ToTable("AspNetRoleClaims", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                        {
                            b.Property<string>("Id")
                                .HasColumnType("text");

                            b.Property<int>("AccessFailedCount")
                                .HasColumnType("integer");

                            b.Property<string>("ConcurrencyStamp")
                                .IsConcurrencyToken()
                                .HasColumnType("text");

                            b.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.Property<bool>("EmailConfirmed")
                                .HasColumnType("boolean");

                            b.Property<bool>("LockoutEnabled")
                                .HasColumnType("boolean");

                            b.Property<DateTimeOffset?>("LockoutEnd")
                                .HasColumnType("timestamp with time zone");

                            b.Property<string>("NormalizedEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.Property<string>("NormalizedUserName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.Property<string>("PasswordHash")
                                .HasColumnType("text");

                            b.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("boolean");

                            b.Property<string>("SecurityStamp")
                                .HasColumnType("text");

                            b.Property<bool>("TwoFactorEnabled")
                                .HasColumnType("boolean");

                            b.Property<string>("UserName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b.HasKey("Id");

                            b.HasIndex("NormalizedEmail")
                                .HasDatabaseName("EmailIndex");

                            b.HasIndex("NormalizedUserName")
                                .IsUnique()
                                .HasDatabaseName("UserNameIndex");

                            b.ToTable("AspNetUsers", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                            b.Property<string>("ClaimType")
                                .HasColumnType("text");

                            b.Property<string>("ClaimValue")
                                .HasColumnType("text");

                            b.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b.HasKey("Id");

                            b.HasIndex("UserId");

                            b.ToTable("AspNetUserClaims", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                        {
                            b.Property<string>("LoginProvider")
                                .HasColumnType("text");

                            b.Property<string>("ProviderKey")
                                .HasColumnType("text");

                            b.Property<string>("ProviderDisplayName")
                                .HasColumnType("text");

                            b.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b.HasKey("LoginProvider", "ProviderKey");

                            b.HasIndex("UserId");

                            b.ToTable("AspNetUserLogins", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                        {
                            b.Property<string>("UserId")
                                .HasColumnType("text");

                            b.Property<string>("RoleId")
                                .HasColumnType("text");

                            b.HasKey("UserId", "RoleId");

                            b.HasIndex("RoleId");

                            b.ToTable("AspNetUserRoles", (string)null);
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                        {
                            b.Property<string>("UserId")
                                .HasColumnType("text");

                            b.Property<string>("LoginProvider")
                                .HasColumnType("text");

                            b.Property<string>("Name")
                                .HasColumnType("text");

                            b.Property<string>("Value")
                                .HasColumnType("text");

                            b.HasKey("UserId", "LoginProvider", "Name");

                            b.ToTable("AspNetUserTokens", (string)null);
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.Order", b =>
                        {
                            b.HasOne("ExMart_Backend.Model.StatusMaster", "ProductStatus")
                                .WithMany("Orders")
                                .HasForeignKey("Product_StatusId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b.HasOne("ExMart_Backend.Model.User", "User")
                                .WithMany("Orders")
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b.Navigation("ProductStatus");

                            b.Navigation("User");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.OrderItem", b =>
                        {
                            b.HasOne("ExMart_Backend.Model.ColourMaster", "Color")
                                .WithMany("OrderItems")
                                .HasForeignKey("ColorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b.HasOne("ExMart_Backend.Model.Order", "Order")
                                .WithMany("OrderItems")
                                .HasForeignKey("OrderId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.HasOne("ExMart_Backend.Model.Product", "Product")
                                .WithMany("OrderItems")
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b.HasOne("ExMart_Backend.Model.SizeMaster", "Size")
                                .WithMany("OrderItems")
                                .HasForeignKey("SizeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b.Navigation("Color");

                            b.Navigation("Order");

                            b.Navigation("Product");

                            b.Navigation("Size");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.ProductImages", b =>
                        {
                            b.HasOne("ExMart_Backend.Model.Product", "Product")
                                .WithMany("ProductImages")
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.Navigation("Product");
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.ColourMaster", b =>
                        {
                            b.Navigation("OrderItems");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.Order", b =>
                        {
                            b.Navigation("OrderItems");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.Product", b =>
                        {
                            b.Navigation("OrderItems");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.SizeMaster", b =>
                        {
                            b.Navigation("OrderItems");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.StatusMaster", b =>
                        {
                            b.Navigation("Orders");
                        });

                    modelBuilder.Entity("ExMart_Backend.Model.User", b =>
                        {
                            b.Navigation("Orders");
                            b.Navigation("ProductImages");
                        });
#pragma warning restore 612, 618
                });
        }
    }
}
